In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv') #csv kyu hai?
df.head(1)

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        89 non-null     object
 1   Model               92 non-null     object
 2   Type                90 non-null     object
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object
 9   DriveTrain          86 non-null     object
 10  Cylinders           88 non-null     object
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object
 16  Fuel.tank.capacity  85 non-null     float64
 17  Passengers          91 non-null     float64
 18  Length              89 non-null     float64
 19  Wheelbase           92 non-null     float64
 20  Width               87 non-null     float64
 21  Turn.circle         88 non-null     float64
 22  Rear.seat.room      89 non-null     float64
 23  Luggage.room        74 non-null     float64
 24  Weight              86 non-null     float64
 25  Origin              88 non-null     object
 26  Make                90 non-null     object
dtypes: float64(18), object(9)
memory usage: 19.7+ KB

In [3]:
df.shape

(93, 27)

In [4]:
#how many null values are present in each column.
df.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [34]:
df['Manufacturer'].head()

0    Acura
1      NaN
2     Audi
3     Audi
4      BMW
Name: Manufacturer, dtype: object

In [6]:
#top 5 manufacturing companies
df['Manufacturer'].value_counts()[:5]

Chevrolet    8
Ford         8
Dodge        6
Mazda        5
Pontiac      5
Name: Manufacturer, dtype: int64

In [7]:
df['Model'].unique()

array(['Integra', 'Legend', '90', '100', '535i', 'Century', 'LeSabre',
       'Roadmaster', 'Riviera', 'DeVille', 'Seville', 'Cavalier',
       'Corsica', 'Camaro', 'Lumina', 'Lumina_APV', 'Astro', 'Caprice',
       'Corvette', 'Concorde', 'LeBaron', 'Imperial', 'Colt', 'Shadow',
       'Spirit', 'Caravan', 'Dynasty', 'Stealth', 'Summit', 'Vision',
       'Festiva', 'Escort', 'Tempo', 'Mustang', 'Probe', 'Aerostar',
       'Taurus', 'Crown_Victoria', 'Metro', 'Storm', 'Prelude', 'Civic',
       'Accord', 'Excel', 'Elantra', 'Scoupe', 'Sonata', 'Q45', 'ES300',
       'SC300', 'Continental', 'Town_Car', '323', 'Protege', '626', 'MPV',
       'RX-7', '190E', '300E', nan, 'Cougar', 'Mirage', 'Diamante',
       'Sentra', 'Altima', 'Quest', 'Maxima', 'Achieva', 'Cutlass_Ciera',
       'Silhouette', 'Eighty-Eight', 'Laser', 'LeMans', 'Sunbird',
       'Firebird', 'Grand_Prix', 'Bonneville', '900', 'SL', 'Justy',
       'Loyale', 'Legacy', 'Swift', 'Tercel', 'Celica', 'Camry', 'Previa',
       'Fox', 'Eurovan', 'Passat', 'Corrado', '240', '850'], dtype=object)

In [8]:
df['Model'].nunique()

92

In [9]:
a=df['Model'].value_counts()
a

MPV              1
LeSabre          1
Mirage           1
RX-7             1
Dynasty          1
                ..
Festiva          1
Century          1
Cutlass_Ciera    1
Mustang          1
Roadmaster       1
Name: Model, Length: 92, dtype: int64

In [10]:
y=df['Model'].value_counts()
for i in y:
    if i==1:
      print('ok')
    else:
        print('print')

ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok

In [11]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
88    False
89    False
90    False
91    False
92    False
Length: 93, dtype: bool

In [12]:
#How to extract the row and column of a particular cell with given condition.
#find the manucfacturer with the highest price.
import pandas as pd
import numpy as np
g=df.loc[df.Price == np.min(df.Price), ['Manufacturer', 'Model', 'Type']]
g

   Manufacturer    Model   Type
30         Ford  Festiva  Small

In [13]:
#find the row and column of the above question

In [14]:
row, col = np.where(df.values == np.max(df.Price))
row,col

(array([58]), array([4]))

In [15]:
df.iat[row[0], col[0]]     #yeh teen cells idhar kyu likha hai

61.9

In [16]:
df.iloc[row[0], col[0]]

61.9

In [17]:
df.loc[1:58]

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
5,Buick,Century,Midsize,14.2,15.7,17.3,22.0,31.0,Driver only,NaN,...,6.0,189.0,105.0,69.0,41.0,28.0,16.0,NaN,USA,Buick Century
6,Buick,LeSabre,Large,19.9,20.8,NaN,19.0,28.0,Driver only,Front,...,6.0,200.0,111.0,74.0,42.0,30.5,17.0,3470.0,USA,Buick LeSabre
7,Buick,Roadmaster,Large,22.6,23.7,24.9,16.0,25.0,Driver only,Rear,...,6.0,216.0,116.0,78.0,45.0,30.5,21.0,4105.0,USA,Buick Roadmaster
8,Buick,Riviera,Midsize,26.3,26.3,26.3,19.0,27.0,Driver only,Front,...,5.0,198.0,108.0,NaN,41.0,26.5,14.0,3495.0,USA,Buick Riviera
9,Cadillac,DeVille,Large,33.0,34.7,36.3,16.0,25.0,Driver only,Front,...,6.0,206.0,114.0,73.0,43.0,35.0,18.0,3620.0,USA,Cadillac DeVille
10,Cadillac,Seville,Midsize,37.5,40.1,42.7,16.0,25.0,Driver & Passenger,Front,...,5.0,204.0,111.0,74.0,44.0,31.0,NaN,3935.0,USA,Cadillac Seville
11,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25.0,36.0,NaN,NaN,...,5.0,182.0,101.0,66.0,38.0,25.0,13.0,2490.0,USA,Chevrolet Cavalier
12,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25.0,34.0,Driver only,Front,...,5.0,184.0,103.0,68.0,39.0,26.0,NaN,2785.0,USA,Chevrolet Corsica
13,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19.0,28.0,Driver & Passenger,Rear,...,4.0,193.0,101.0,74.0,43.0,25.0,13.0,3240.0,USA,Chevrolet Camaro
14,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,NaN,29.0,None,Front,...,6.0,NaN,108.0,71.0,NaN,28.5,16.0,3195.0,USA,Chevrolet Lumina
15,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18.0,23.0,None,Front,...,7.0,178.0,110.0,74.0,44.0,30.5,NaN,3715.0,USA,Chevrolet Lumina_APV
16,Chevrolet,Astro,Van,14.7,16.6,18.6,15.0,20.0,None,4WD,...,8.0,194.0,111.0,78.0,42.0,33.5,NaN,4025.0,USA,Chevrolet Astro
17,Chevrolet,Caprice,Large,18.0,18.8,19.6,17.0,26.0,Driver only,Rear,...,6.0,214.0,116.0,77.0,42.0,29.5,20.0,3910.0,USA,Chevrolet Caprice
18,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17.0,25.0,Driver only,Rear,...,2.0,179.0,96.0,74.0,43.0,NaN,NaN,3380.0,NaN,Chevrolet Corvette
19,NaN,Concorde,Large,18.4,18.4,18.4,20.0,28.0,Driver & Passenger,Front,...,6.0,203.0,113.0,74.0,NaN,31.0,15.0,3515.0,USA,Chrylser Concorde
20,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23.0,28.0,Driver & Passenger,Front,...,6.0,183.0,104.0,68.0,41.0,30.5,14.0,3085.0,USA,Chrysler LeBaron
21,Chrysler,Imperial,Large,29.5,29.5,29.5,20.0,26.0,Driver only,Front,...,6.0,203.0,110.0,69.0,44.0,36.0,17.0,3570.0,USA,Chrysler Imperial
22,Dodge,Colt,Small,7.9,9.2,10.6,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,32.0,NaN,11.0,2270.0,USA,Dodge Colt
23,Dodge,Shadow,Small,8.4,11.3,14.2,23.0,29.0,Driver only,Front,...,5.0,172.0,97.0,67.0,38.0,26.5,NaN,2670.0,USA,Dodge Shadow
24,Dodge,Spirit,Compact,11.9,13.3,14.7,22.0,27.0,Driver only,Front,...,6.0,181.0,104.0,68.0,39.0,30.5,NaN,2970.0,USA,Dodge Spirit
25,Dodge,Caravan,Van,NaN,19.0,24.4,17.0,21.0,Driver only,4WD,...,7.0,175.0,112.0,72.0,42.0,26.5,NaN,3705.0,USA,Dodge Caravan
26,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21.0,NaN,Driver only,Front,...,6.0,192.0,105.0,69.0,42.0,30.5,16.0,3080.0,USA,Dodge Dynasty
27,Dodge,Stealth,Sporty,18.5,25.8,33.1,NaN,24.0,Driver only,4WD,...,4.0,180.0,97.0,NaN,40.0,20.0,11.0,3805.0,USA,Dodge Stealth
28,Eagle,Summit,Small,7.9,12.2,16.5,29.0,33.0,None,Front,...,5.0,174.0,98.0,66.0,36.0,26.5,11.0,2295.0,USA,Eagle Summit
29,Eagle,Vision,Large,NaN,19.3,21.2,20.0,28.0,Driver & Passenger,Front,...,6.0,202.0,113.0,74.0,40.0,30.0,15.0,3490.0,USA,Eagle Vision
30,Ford,Festiva,Small,6.9,7.4,7.9,31.0,33.0,NaN,Front,...,4.0,141.0,90.0,63.0,33.0,26.0,12.0,1845.0,USA,Ford Festiva
31,Ford,Escort,Small,8.4,10.1,11.9,23.0,30.0,None,Front,...,5.0,171.0,98.0,67.0,36.0,28.0,12.0,2530.0,USA,Ford Escort
32,Ford,Tempo,Compact,10.4,11.3,12.2,22.0,27.0,None,Front,...,5.0,177.0,100.0,68.0,NaN,27.5,13.0,NaN,USA,NaN
33,Ford,Mustang,Sporty,10.8,15.9,21.0,22.0,29.0,Driver only,Rear,...,4.0,180.0,101.0,68.0,40.0,24.0,12.0,NaN,USA,Ford Mustang
34,Ford,Probe,Sporty,12.8,14.0,15.2,NaN,30.0,Driver only,Front,...,4.0,179.0,103.0,70.0,38.0,23.0,18.0,2710.0,USA,Ford Probe
35,Ford,Aerostar,Van,14.5,19.9,25.3,15.0,20.0,Driver only,4WD,...,7.0,176.0,119.0,72.0,45.0,30.0,NaN,3735.0,USA,Ford Aerostar
36,Ford,Taurus,Midsize,15.6,20.2,24.8,21.0,30.0,Driver only,Front,...,5.0,192.0,106.0,71.0,40.0,27.5,18.0,3325.0,USA,Ford Taurus
37,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18.0,26.0,Driver only,Rear,...,6.0,212.0,114.0,78.0,43.0,30.0,21.0,3950.0,USA,Ford Crown_Victoria
38,Geo,Metro,Small,6.7,8.4,10.0,46.0,50.0,None,Front,...,4.0,151.0,93.0,63.0,34.0,27.5,10.0,1695.0,non-USA,Geo Metro
39,Geo,Storm,Sporty,11.5,12.5,13.5,30.0,36.0,Driver only,Front,...,4.0,164.0,97.0,NaN,37.0,24.5,11.0,2475.0,non-USA,Geo Storm
40,Honda,Prelude,Sporty,17.0,19.8,22.7,24.0,31.0,Driver & Passenger,Front,...,4.0,175.0,100.0,70.0,39.0,23.5,8.0,2865.0,non-USA,Honda Prelude
41,Honda,Civic,Small,8.4,12.1,15.8,42.0,46.0,Driver only,Front,...,4.0,173.0,NaN,67.0,36.0,28.0,12.0,NaN,non-USA,Honda Civic
42,Honda,Accord,Compact,13.8,17.5,21.2,24.0,31.0,Driver & Passenger,Front,...,4.0,185.0,107.0,67.0,41.0,28.0,14.0,3040.0,non-USA,Honda Accord
43,Hyundai,Excel,Small,6.8,8.0,9.2,29.0,33.0,None,Front,...,5.0,168.0,94.0,63.0,35.0,26.0,11.0,2345.0,non-USA,Hyundai Excel
44,Hyundai,Elantra,Small,9.0,10.0,11.0,NaN,29.0,None,Front,...,5.0,172.0,98.0,66.0,36.0,28.0,12.0,2620.0,non-USA,Hyundai Elantra
45,Hyundai,Scoupe,NaN,9.1,10.0,11.0,26.0,34.0,None,Front,...,4.0,166.0,94.0,64.0,34.0,23.5,9.0,2285.0,non-USA,NaN
46,Hyundai,Sonata,Midsize,12.4,13.9,15.3,20.0,27.0,None,Front,...,5.0,184.0,104.0,69.0,41.0,31.0,NaN,2885.0,NaN,Hyundai Sonata
47,Infiniti,Q45,Midsize,45.4,47.9,NaN,17.0,22.0,NaN,Rear,...,5.0,200.0,113.0,72.0,42.0,29.0,15.0,4000.0,non-USA,Infiniti Q45
48,Lexus,ES300,Midsize,27.5,28.0,28.4,18.0,24.0,Driver only,Front,...,5.0,188.0,103.0,70.0,40.0,27.5,14.0,3510.0,non-USA,Lexus ES300
49,NaN,SC300,Midsize,34.7,35.2,35.6,18.0,23.0,Driver & Passenger,Rear,...,4.0,191.0,106.0,71.0,39.0,25.0,9.0,3515.0,non-USA,Lexus SC300
50,Lincoln,Continental,Midsize,33.3,34.3,35.3,17.0,26.0,Driver & Passenger,NaN,...,6.0,205.0,109.0,73.0,42.0,30.0,19.0,3695.0,USA,Lincoln Continental
51,Lincoln,Town_Car,Large,34.4,36.1,37.8,18.0,26.0,Driver & Passenger,Rear,...,NaN,219.0,117.0,77.0,45.0,31.5,22.0,4055.0,USA,Lincoln Town_Car
52,Mazda,323,Small,7.4,8.3,9.1,29.0,37.0,None,Front,...,4.0,164.0,97.0,66.0,34.0,27.0,16.0,2325.0,non-USA,Mazda 323
53,Mazda,Protege,Small,10.9,11.6,12.3,28.0,36.0,None,Front,...,5.0,172.0,98.0,66.0,36.0,26.5,13.0,2440.0,non-USA,Mazda Protege
54,Mazda,626,Compact,14.3,16.5,18.7,26.0,34.0,Driver only,Front,...,5.0,184.0,103.0,69.0,40.0,29.5,14.0,2970.0,non-USA,Mazda 626
55,Mazda,MPV,Van,16.6,19.1,21.7,18.0,24.0,None,4WD,...,7.0,190.0,110.0,72.0,39.0,27.5,NaN,3735.0,non-USA,Mazda MPV
56,Mazda,RX-7,Sporty,32.5,32.5,32.5,17.0,25.0,Driver only,NaN,...,2.0,169.0,96.0,69.0,NaN,NaN,NaN,NaN,non-USA,Mazda RX-7
57,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,NaN,29.0,Driver only,Rear,...,5.0,175.0,105.0,67.0,34.0,26.0,12.0,2920.0,NaN,Mercedes-Benz 190E
58,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19.0,25.0,Driver & Passenger,Rear,...,5.0,NaN,110.0,69.0,37.0,NaN,15.0,3525.0,non-USA,Mercedes-Benz 300E

In [18]:
#how to rename a specific column in a data frame
df.columns.values[2] = "CarType"
df

,Manufacturer,Model,CarType,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,21.0,None,Front,...,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,30.0,None,Front,...,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,25.0,None,Front,...,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

In [19]:
#how to replace missing values of multiple numeric column with the mean value
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
df_out

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

In [20]:
df.describe()

,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,91.000000,93.000000,84.000000,91.000000,91.000000,86.000000,90.000000,87.000000,85.000000,91.000000,89.000000,92.000000,87.000000,88.000000,89.000000,74.000000,86.000000
mean,17.118605,19.616484,21.459091,22.404762,29.065934,2.658242,144.000000,5276.666667,2355.000000,16.683529,5.076923,182.865169,103.956522,69.448276,38.954545,27.853933,13.986486,3104.593023
std,8.485787,9.724280,10.401836,5.841520,5.370293,1.045845,53.455204,605.554811,486.916616,3.375748,1.045953,14.792651,6.856317,3.778023,3.304157,3.018129,3.120824,600.129993
min,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,11.400000,12.350000,14.900000,18.000000,26.000000,1.800000,100.750000,4800.000000,2017.500000,14.500000,4.000000,174.000000,98.000000,67.000000,36.000000,26.000000,12.000000,2647.500000
50%,14.900000,17.700000,21.000000,21.000000,28.000000,2.300000,140.000000,5200.000000,2360.000000,16.500000,5.000000,181.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3085.000000
75%,19.900000,23.500000,24.400000,25.000000,31.000000,3.250000,170.000000,5787.500000,2565.000000,19.000000,6.000000,192.000000,110.000000,72.000000,42.000000,30.000000,16.000000,3567.500000
max,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

In [21]:
df['Min.Price'].mean()

17.11860465116279

In [22]:
df['Max.Price'].mean()

21.459090909090918

In [23]:
#how to filter every nth row in a dataframe

In [24]:
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model  CarType
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [25]:
#how to create a primary key index by combining relevent columns.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.unique)
df[['Manufacturer', 'Model', 'Type']].nunique()

<bound method Index.unique of Index(['Acura_Integra_Small', 'missing_Legend_Midsize', 'Audi_90_Compact',
       'Audi_100_Midsize', 'BMW_535i_Midsize', 'Buick_Century_Midsize',
       'Buick_LeSabre_Large', 'Buick_Roadmaster_Large',
       'Buick_Riviera_Midsize', 'Cadillac_DeVille_Large',
       'Cadillac_Seville_Midsize', 'Chevrolet_Cavalier_Compact',
       'Chevrolet_Corsica_Compact', 'Chevrolet_Camaro_Sporty',
       'Chevrolet_Lumina_Midsize', 'Chevrolet_Lumina_APV_Van',
       'Chevrolet_Astro_Van', 'Chevrolet_Caprice_Large',
       'Chevrolet_Corvette_Sporty', 'missing_Concorde_Large',
       'Chrysler_LeBaron_Compact', 'Chrysler_Imperial_Large',
       'Dodge_Colt_Small', 'Dodge_Shadow_Small', 'Dodge_Spirit_Compact',
       'Dodge_Caravan_Van', 'Dodge_Dynasty_Midsize', 'Dodge_Stealth_Sporty',
       'Eagle_Summit_Small', 'Eagle_Vision_Large', 'Ford_Festiva_Small',
       'Ford_Escort_Small', 'Ford_Tempo_Compact', 'Ford_Mustang_Sporty',
       'Ford_Probe_Sporty', 'Ford_Aerostar_Van', 'Ford_Taurus_Midsize',
       'Ford_Crown_Victoria_Large', 'Geo_Metro_Small', 'Geo_Storm_Sporty',
       'Honda_Prelude_Sporty', 'Honda_Civic_Small', 'Honda_Accord_Compact',
       'Hyundai_Excel_Small', 'Hyundai_Elantra_Small',
       'Hyundai_Scoupe_missing', 'Hyundai_Sonata_Midsize',
       'Infiniti_Q45_Midsize', 'Lexus_ES300_Midsize', 'missing_SC300_Midsize',
       'Lincoln_Continental_Midsize', 'Lincoln_Town_Car_Large',
       'Mazda_323_Small', 'Mazda_Protege_Small', 'Mazda_626_Compact',
       'Mazda_MPV_Van', 'Mazda_RX-7_Sporty', 'Mercedes-Benz_190E_Compact',
       'Mercedes-Benz_300E_Midsize', 'Mercury_missing_Sporty',
       'Mercury_Cougar_Midsize', 'Mitsubishi_Mirage_Small',
       'Mitsubishi_Diamante_Midsize', 'Nissan_Sentra_Small',
       'Nissan_Altima_Compact', 'Nissan_Quest_Van', 'Nissan_Maxima_Midsize',
       'Oldsmobile_Achieva_Compact', 'Oldsmobile_Cutlass_Ciera_Midsize',
       'Oldsmobile_Silhouette_Van', 'Oldsmobile_Eighty-Eight_Large',
       'Plymouth_Laser_Sporty', 'Pontiac_LeMans_Small',
       'Pontiac_Sunbird_Compact', 'Pontiac_Firebird_missing',
       'Pontiac_Grand_Prix_Midsize', 'Pontiac_Bonneville_Large',
       'Saab_900_Compact', 'Saturn_SL_Small', 'Subaru_Justy_Small',
       'Subaru_Loyale_Small', 'Subaru_Legacy_Compact', 'Suzuki_Swift_missing',
       'Toyota_Tercel_Small', 'Toyota_Celica_Sporty', 'Toyota_Camry_Midsize',
       'Toyota_Previa_Van', 'Volkswagen_Fox_Small', 'Volkswagen_Eurovan_Van',
       'Volkswagen_Passat_Compact', 'Volkswagen_Corrado_Sporty',
       'Volvo_240_Compact', 'missing_850_Midsize'],
      dtype='object')>

Manufacturer    32
Model           93
Type             7
dtype: int64

In [26]:
#how to get the row number of the nth largest value in a column.
df = pd.DataFrame(np.random.randint(1, 9, 27).reshape(9,-1), columns=list('abc'))
df

   a  b  c
0  5  1  7
1  5  4  4
2  4  2  5
3  3  3  4
4  6  3  1
5  8  3  8
6  7  3  6
7  3  2  2
8  1  1  1

In [27]:
#Solution
y=df['a'].max()
y

8

In [28]:
index=df.index
condition=df['a']==y
largest=index[condition]
largest

Int64Index([5], dtype='int64')

In [29]:
#how to reverse row of dataframe
df = pd.DataFrame(np.arange(25).reshape(5, -1))
# Solution 1
df.iloc[::-1, :]

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [30]:
#how to swap 2 rows of a dataframe using function.
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24